Expand codeowner teams
home-assistant/service-hub pull request #186
Opened 2023-06-02 23:35 UTC by raman325

As discussed, this updates the codeowners checks to expand teams into user lists

2023-06-06 08:31 UTC, ludeeus requested changes

2023-06-06 08:31 UTC, ludeeus commented on services/bots/src/github-webhook/utils/teams.ts
> +export const expandTeams = async (
I think we should extend [`WebhookContext`](https://github.com/home-assistant/service-hub/blob/main/services/bots/src/github-webhook/github-webhook.model.ts#L36) with this function and change the name to `expandOrganizationTeams`

2023-06-06 08:31 UTC, ludeeus commented on services/bots/src/github-webhook/utils/teams.ts
> +          org: Organization.HOME_ASSISTANT,
Once moved, use `org: this.organization,` here

2023-06-06 08:31 UTC, ludeeus commented on services/bots/src/github-webhook/utils/teams.ts
> +  const users = usersAndTeams.filter((name) => !name.startsWith(TEAM_PREFIX));
This would need an adjustment to use ``${this.organization}${ORG_TEAM_SEP}``

2023-06-06 13:12 UTC, ludeeus commented on services/bots/src/github-webhook/utils/teams.ts
> +export const expandTeams = async (
Extend was my initial thought, but if we for the most part pass it, we can continue with that here.

2023-06-06 13:29 UTC, raman325 commented
OK done with tweaks, realized I could simplify things

2023-06-06 13:34 UTC, raman325 commented
OK **NOW** I'm done 😅

2023-06-16 21:24 UTC, ludeeus approved these changes
Thanks!

2023-06-16 21:24 UTC, merged